## **定义数组**

In [1]:
import numpy as np
#一维数组
a = np.array([1, 2, 3])
print(a)
#多维数组
b = np.array([[1, 2], [3, 4]])
print(b)

[1 2 3]
[[1 2]
 [3 4]]


## **下面的代码显示了创建数组的4种不同方法**
最基本的方法是将序列传递给Numpy的`array()`函数; 你可以传递任何序列，而不仅仅是常见的列表数据类型

In [2]:
# 1D Array 其他的方法
a = np.array([0, 1, 2, 3, 4])
b = np.array((0, 1, 2, 3, 4))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5)

print(a) # >>>[0 1 2 3 4]
print(b) # >>>[0 1 2 3 4]
print(c) # >>>[0 1 2 3 4]
print(d) # >>>[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
print(a[3]) # >>>3

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
3


## **如何使用多维数组表示矩阵和更多的信息**

In [3]:
# MD Array
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
 
print(a[2,4]) # >>>25

#为了创建一个2D（二维）数组，我们传递一个列表的列表（或者是一个序列的序列）给array()函数。
#如果我们想要一个3D（三维）数组，我们就要传递一个列表的列表的列表，
#如果是一个4D（四维）数组，那就是列表的列表的列表的列表，以此类推

#查看数组的某些信息
print(type(a)) # >>><class 'numpy.ndarray'>
print(a.dtype) # >>>int64
print(a.size) # >>>25
print(a.shape) # >>>(5, 5)
print(a.itemsize) # >>>8
print(a.ndim) # >>>2
print(a.nbytes) # >>>200

25
<class 'numpy.ndarray'>
int32
25
(5, 5)
4
2
100


## **如何改变数组的形状**
建议使用Numpy的`reshape()`函数对数组形状进行重新定义

In [4]:
a = np.arange(25)
a = a.reshape((5, 5))

b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
b = b.reshape((5,5))
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 62  1 14  2]
 [56 79  2  1 45]
 [ 4 92  5 55 63]
 [43 35  6 53 24]
 [56  3 56 44 78]]


## **arry的属性**

In [5]:
a.shape # 数组形状

(5, 5)

In [6]:
a.ndim # 数组维度

2

In [7]:
a.dtype # 数组中元素类型

dtype('int32')

In [8]:
a.itemsize # 数组中每个元素的字节大小

4

In [9]:
a.size # 数组中元素个数

25

In [10]:
type(a) # 数组类型

numpy.ndarray

In [11]:
arr = np.arange(36).reshape(3, 4, 3) # 改变数组形状
print(arr)
print(arr.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
(3, 4, 3)


## **一些定义数组中值的函数**

In [12]:
a = np.zeros((2,2))   # 构造一个所有元素均为0的数组，size=(2,2)
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # 构造一个所有元素均为1的数组，size=(1,2)
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # 构造一个所有元素均为7的数组，size=(2,2)
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # 构造一个对角线元素为1，其余元素为0的二维数组
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # 构造一个数组，数组中的元素是均匀分布的随机数，取值[0.0, 1.0), size=(2,2)
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.56435498 0.39821432]
 [0.83403178 0.84249264]]


## **如何对数组切片，从而选择需要的部分元素**

In [13]:
# MD slicing
arr = np.arange(16).reshape(4,4)
print(arr)
print(arr[0, 1:4]) # 取第1行的2-4列元素
print(arr[1:4, 0]) # 取2-3行的第1列元素
print(arr[::2,::2]) # 每隔一行，每隔一列显示重叠元素
print(arr[:, 1]) # 取所有行的第2列元素

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[1 2 3]
[ 4  8 12]
[[ 0  2]
 [ 8 10]]
[ 1  5  9 13]


## **条件索引**

In [14]:
indices = np.where(arr > 10)  
filtered_arr = arr[indices]  
print(filtered_arr)

[11 12 13 14 15]


## **Numpy基本运算**

In [15]:
import numpy as np 
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], [7.0, 8.0]]) 
sum = a + b  # 加法
difference = a - b  # 减法
product = a * b  # 乘法
quotient = a / b  # 除法
matrix_product = a.dot(b) # 矩阵乘法

print("a + b = \n", sum )
print("a - b = \n", difference) 
print("a * b = \n", product)
print( "a / b = \n", quotient) 
print("a.dot(b) = \n", matrix_product)

a + b = 
 [[ 6.  8.]
 [10. 12.]]
a - b = 
 [[-4. -4.]
 [-4. -4.]]
a * b = 
 [[ 5. 12.]
 [21. 32.]]
a / b = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
a.dot(b) = 
 [[19. 22.]
 [43. 50.]]


In [16]:
# Basic Operators
a = np.arange(25)
a = a.reshape((5, 5))

b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
b = b.reshape((5,5))

print(a + b) #同位置的元素相加
print(a - b) #同位置的元素相减
print(a * b) #同位置的元素相乘
print(a / b) #同位置的元素除法
print(a ** 2) #每个元素求平方
print(a < b)  #同位置的元素的大小关系（若a[i,j]< b[i,j],则c[i,j]为True）
print(a > b)
print(a.dot(b)) #点乘

[[ 10  63   3  17   6]
 [ 61  85   9   9  54]
 [ 14 103  17  68  77]
 [ 58  51  23  71  43]
 [ 76  24  78  67 102]]
[[-10 -61   1 -11   2]
 [-51 -73   5   7 -36]
 [  6 -81   7 -42 -49]
 [-28 -19  11 -35  -5]
 [-36  18 -34 -21 -54]]
[[   0   62    2   42    8]
 [ 280  474   14    8  405]
 [  40 1012   60  715  882]
 [ 645  560  102  954  456]
 [1120   63 1232 1012 1872]]
[[0.         0.01612903 2.         0.21428571 2.        ]
 [0.08928571 0.07594937 3.5        8.         0.2       ]
 [2.5        0.11956522 2.4        0.23636364 0.22222222]
 [0.34883721 0.45714286 2.83333333 0.33962264 0.79166667]
 [0.35714286 7.         0.39285714 0.52272727 0.30769231]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
[[ True  True False  True False]
 [ True  True False False  True]
 [False  True False  True  True]
 [ True  True False  True  True]
 [ True False  True  True  True]]
[[False False  True False  True]
 [False False  True  

In [17]:
# NumPy还提供了一些别的用于处理数组的好用的运算符。

a = np.arange(1, 10) #array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.sum(a)) # 求和
print(np.mean(a)) # 平均值
print(np.max(a)) # 最大值
print(np.min(a)) # 最小值
print(np.power(a, 2)) # 幂运算
print(np.sqrt(a)) # 平方根
print(np.exp(a)) # 指数函数
print(np.log(a)) # 对数函数

45
5.0
9
1
[ 1  4  9 16 25 36 49 64 81]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


## **广播运算**

In [18]:
print(a+10)
print(a*10)

[11 12 13 14 15 16 17 18 19]
[10 20 30 40 50 60 70 80 90]


## **向量排序**

In [19]:
a = np.arange(10)
sorted_a = np.sort(a)
print(sorted_a)

[0 1 2 3 4 5 6 7 8 9]


## **向量布尔运算**

In [20]:
print(a>5) # 向量比较
print(a[a>5]) # 满足条件的向量元素

[False False False False False False  True  True  True  True]
[6 7 8 9]
